### ISSUE TITLE
TimerTrigger singleton seems to contend between deployment slots

### ISSUE THREAD

**Issue by EmilBechMadsen** [Azure/azure-webjobs-sdk-extensions#56] opened 2016-03-19 13:44 UTC
Hi. I came across the situation in which a webjob set to run with a TimerTrigger on both a staging deployment slot and production, will contend for the same singleton. I doubt that this is intentional?

Steps to reproduce:
1. Get a web app going with an On-Demand Webjob with a timer trigger and verbose logging enabled..
2. Create a deploymentslot, publish the same webjob to that deployment slot.
3. Whichever webjob was started first will have the lock, and the other won't be able to obtain it.

If I'm doing something wrong or it's supposed to contend with one another, let me know, otherwise I guess the bug is on your end :)

**Comment by mathewc** [comment] 2016-03-21 04:24
For a single host (HostId by default derived from the fully qualified assembly name of your job host) the lock is shared. That means that if you're running the same host on multiple machines or environments, they all use the same lock.

See this issue here https://github.com/Azure/azure-webjobs-sdk-extensions/issues/31 for more details. It explains ways to achieve separation if that is what you desire between different environments.

**Comment by mathewc** [comment] 2016-05-10 03:28
Closing because this is expected behavior based on what I said above.

**Closed by mathewc** 2016-05-10 03:28 UTC
Labels: bug

**Comment by pjt33** [comment] 2016-06-22 14:24
In the particular case of deployment slots, and on the assumption that you don't need the jobs to run in the deployment slot but only in the live deployment, there is also the option of setting a slot-local application setting `WEBJOBS_STOPPED` to `1`.
