### ISSUE TITLE
CosmosDbTrigger not scaling out workers

### ISSUE THREAD

**Issue by smokedlinq** [Azure/azure-webjobs-sdk-extensions#766] opened 2022-03-14 18:16 UTC
Noticing our change feed is running slow and the workers are not scaling out. We have millions of documents left to process (~36m) and it is still just running on the 3 workers that we configured as a minimum.

I checked the ScaleControllerLogs and found this:

```
Trigger type 'cosmosDBTrigger' is unrecognized or has an invalid/incomplete trigger configuration. 
The scale controller will not be able to directly activate or scale function 'ChangeFeedTrigger'
```

Not sure what's causing this.

#### Expected behavior

The scaler controller adds workers when there is a large backlog of change feed documents.

#### Actual behavior

The worker count / partition count does not change (I checked with the ChangeFeedEstimator).

#### Related information 

Packages:
```xml
<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.25.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="4.0.0-preview3" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.0" />
```

Function App:
```csharp
[FunctionName(nameof(ChangeFeedTrigger))]
public async Task RunAsync([CosmosDBTrigger(
    databaseName: "Database",
    containerName: "Container",
    Connection = "CosmosConnectionString",
    CreateLeaseContainerIfNotExists = true,
    LeaseDatabaseName = "Leases",
    LeaseContainerName = "Database-Container",
    LeaseContainerPrefix = nameof(ChangeFeedTrigger),
    MaxItemsPerInvocation = 5000,
    FeedPollDelay = 5000
    )]IReadOnlyList<Document> documents,
    CancellationToken cancellationToken)
{
}
```

**Comment by v-bbalaiagar** [comment] 2022-03-21 15:22
Hi @ealsur, Could you please look into this issue

**Comment by ealsur** [comment] 2022-03-21 18:42
This is by design, the 4.0.0 extension is in preview https://azure.microsoft.com/en-us/updates/public-preview-of-v4-cosmos-db-extensions-for-azure-functions/

There is no support for dynamic scaling as the Functions' component that deals with that is not released yet.

**Comment by v-bbalaiagar** [comment] 2022-03-22 09:42
Hi @smokedlinq , Closing this issue as this is by design, please feel free to reach back to us in case of any further queries related to this issue.

**Closed as completed by v-bbalaiagar** 2022-03-22 09:42 UTC
