### ISSUE TITLE
How to pass parameter using Cosmosclient object and update the property LimitToEndpoint

### ISSUE THREAD

**Issue by bandarum** [Azure/azure-webjobs-sdk-extensions#727] opened 2021-06-08 02:28 UTC
var client = new CosmosClient(endpoint, masterKey, new CosmosClientOptions()
{
LimitToEndpoint = true,
ConnectionMode = Microsoft.Azure.Cosmos.ConnectionMode.Gateway
});
LimitToEndpoint = true,

**Comment by ealsur** [comment] 2021-09-03 19:35
Duplicate of https://github.com/Azure/azure-webjobs-sdk-extensions/issues/728

**Comment by v-anvari** [comment] 2021-10-18 10:20
Closing the issue as duplicate

**Closed as completed by v-anvari** 2021-10-18 10:20 UTC
