### ISSUE TITLE
Function app settings not read when a function is developed in portal using Cosmos DB Trigger

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-webjobs-sdk-extensions#322] opened 2017-11-01 22:38 UTC
_From @baskar3078 on November 1, 2017 2:49_

When we develop a function using Cosmos DB Trigger in azure portal, the database and collection names are not read from function application settings in function.json file.

#### Investigative information
https://stackoverflow.com/questions/47043182/azure-functions-function-json-cosmos-trigger

#### Repro steps

1. Create a function using CosmosDB Trigger portal
2. Add an function application setting with Key - "cosmos-triggers-database-name" and any value
3. Update the function.json as below

```json
{
  "bindings": [
    {
      "type": "cosmosDBTrigger",
      "name": "inputDocs",
      "direction": "in",
      "leaseDatabaseName": "leases",
      "leaseCollectionName": "MyCosmosCollection-myFunction",
      "connectionStringSetting": "CosmosTriggers-SourceAdapter",
      "databaseName": "%cosmos-triggers-database-name%",
      "collectionName": "MyCosmosCollection",
      "createLeaseCollectionIfNotExists": true
    }
  ],
  "disabled": false
}
```
4. Save and run the function

#### Expected behavior
Expected behavior is to read the document from Cosmos DB.

#### Actual behavior
```
Function ($myFunction) Error: The listener for function 'Functions.myFunction' was unable to start.
 Microsoft.Azure.WebJobs.Extensions.DocumentDB: Either the source collection 'MyCosmosCollection' (in database '%cosmos-triggers-database-name%') or the lease collection 'MyCosmosCollection-myFunction' (in database 'leases') does not exist. Both collections must exist before the listener starts. To automatically create the lease collection, set 'CreateLeaseCollectionIfNotExists' to 'true'. Microsoft.Azure.Documents.Client: Message: {"Errors":["Resource Not Found"]}
 ActivityId: b00f7802-fccb-47eb-972d-0bd70ec896c1, Request URI: rntbd://bn6prdddc05-docdb-1.documents.azure.com:14639/apps/6628b461-75d4-4e4a-9897-ada4076dc30c/services/1b0fc27a-de15-45cf-a1b2-ebfce044d1e2/partitions/34cfee55-54aa-4e31-81f4-08cf1bfdf62f/replicas/131523094168492638s/.
 Session Id: 092ccb7ce9104407bf56c26a5cc8b119
 Timestamp: 2017-10-31T19:13:03.914Z
```

#### Known workarounds

We need to explicitly mention the database and collection name in function.json file.

#### Related information 
https://stackoverflow.com/questions/47043182/azure-functions-function-json-cosmos-trigger

_Copied from original issue: Azure/azure-webjobs-sdk-script#2086_

**Comment by ahmelsayed** [comment] 2017-11-01 22:38
This issue was moved to Azure/azure-webjobs-sdk#1412

**Comment by ahmelsayed** [comment] 2017-11-01 22:38
oops sorry moved to the wrong repo

**Comment by paulbatum** [comment] 2017-11-17 01:38
@ealsur can you take a look at this one?

**Comment by ealsur** [comment] 2017-11-17 09:51
@paulbatum I believe this is related to Issue https://github.com/Azure/azure-webjobs-sdk-extensions/issues/316 a fix was done but I'm not sure if it was deployed.

**Comment by paulbatum** [comment] 2017-11-22 23:08
Ahh that seems likely yes. I don't think its deployed yet, @brettsam is handling that.

**Comment by alohaninja** [comment] 2017-12-22 15:38
@brettsam any update on this? Just curious if we can start using variables for azure function slots. Thanks for the help!

**Comment by brettsam** [comment] 2018-01-03 16:53
Not yet -- the work is in but we haven't deployed. Expect it within a couple of weeks. I'll try to remember to update this issue when it's released.

**Comment by paulbatum** [comment] 2018-02-07 19:02
The fix for this should be deployed. If the issue is still occurring please let us know.

**Comment by alohaninja** [comment] 2018-02-09 17:28
@paulbatum @brettsam I tried using an environment variable, this time it does not error out, but my cosmos DB trigger is never fired. I just switched it back to static string and it works fine. Seems like it's not playing well yet with CFP. Hope someone can look into this...cheers!

**Comment by ealsur** [comment] 2018-02-09 19:06
@paulbatum could this fix still be queued or being deployed? I tried to repro and the values were not being replaced, though the checkin code contained the unit tests for this scenario.

**Comment by ealsur** [comment] 2018-02-12 14:15
@alohaninja I think I found it, seems like using `%` works for environment values, but if you are reading from the Configuration settings, use the configuration setting name directly without `%`. Please let me know if it worked.

**Comment by paulbatum** [comment] 2018-02-12 18:14
@ealsur this commit is in the dev branch, i.e. in functions v2.  Is this a v2 only issue?

**Comment by brettsam** [comment] 2018-02-13 15:30
https://github.com/Azure/azure-webjobs-sdk-extensions/commit/e635c1210140bfae36c47c75d1c363f0484f5b39 is the `v2.x` version of this commit.

@ealsur, what do you mean by Configuration settings? Can you give some examples of what does/doesn't work?

**Comment by ealsur** [comment] 2018-02-13 15:35
@brettsam I corrected myself on a previous comment, the NameResolver is working to replace Application Settings values. But it's not with the `%`, but rather with the name of the setting. Like the `ConnectionStringSetting` works.

I guess the `%` would work for Environment Values.

@alohaninja Can you confirm if using the name of the setting works without the `%`?

**Comment by alohaninja** [comment] 2018-02-16 20:48
OK - so it works without the `%`, but the settings are not connection strings so this is not consistent behavior. Also I'd like to use `%my-env-var%-trigger` to have more control over the value pattern. 

The current implementation does not seem intuitive or consistent, if I happen to use a value that overlaps with an existing environment variable name it will cause issues as a developer you didn't know about the convention and you didn't explicitly provide `%` to indicate you are retrieving a stored value. 

Either way - we're getting closer, appreciate you looking into this as we can still make use of the feature when it gets solidified.

**Comment by ealsur** [comment] 2018-02-16 22:00
Is the `AutoResolve` logic defined somewhere @brettsam ? Ideally we would like to mimic it (since it doesn't work for Triggers) but it seems to be more than just using the NameResolver.

**Comment by brettsam** [comment] 2018-02-16 22:35
I was confused as well. I took a look and have submitted #370 which should fix it.

There were 2 things:
- The NameResolver keys won't contain %%. They basically just do a straight lookup. That's why the tests passed.
- You need to use the `ResolveWholeString` extension in order to evaluate with the %%.

**Closed** 2018-03-07 23:16 UTC
